# ─────────────────────────────────────────────────────────────────
# Sync JWT Configuration from .env to .env.docker
# ─────────────────────────────────────────────────────────────────
# This script copies JWT/auth settings from your local .env file
# to .env.docker, keeping Docker configuration in sync.
#
# Usage:
#   .\scripts\sync-docker-env.ps1
#   npm run docker:sync
# ─────────────────────────────────────────────────────────────────

$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path))
$envFile = Join-Path $rootDir ".env"
$envDockerFile = Join-Path $rootDir ".env.docker"

# Check if .env exists
if (-not (Test-Path $envFile)) {
    Write-Error "Error: .env file not found at $envFile"
    exit 1
}

# Read .env file and parse variables
$envVars = @{}
Get-Content $envFile | ForEach-Object {
    $line = $_.Trim()
    # Skip comments and empty lines
    if ($line -and -not $line.StartsWith("#")) {
        $parts = $line -split "=", 2
        if ($parts.Length -eq 2) {
            $envVars[$parts[0].Trim()] = $parts[1].Trim()
        }
    }
}

# JWT variables to sync
$jwtVars = @(
    "JWT_ISSUER",
    "JWT_AUDIENCE", 
    "JWT_ALGORITHM",
    "JWT_SECRET",
    "JWT_PUBLIC_KEY",
    "JWT_JWKS_URI"
)

# Build .env.docker content
$dockerEnvContent = @"
# ─────────────────────────────────────────────────────────────────
# Docker Environment Configuration
# ─────────────────────────────────────────────────────────────────
# Auto-generated by sync-docker-env.ps1
# Last synced: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# ─────────────────────────────────────────────────────────────────

# Application
NODE_ENV=development
PORT=3000

# PostgreSQL (Docker internal)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=backend_dev

# ─────────────────────────────────────────────────────────────────
# JWT / Authentication (synced from .env)
# ─────────────────────────────────────────────────────────────────
"@

# Add JWT variables
foreach ($var in $jwtVars) {
    if ($envVars.ContainsKey($var) -and $envVars[$var]) {
        $dockerEnvContent += "`n$var=$($envVars[$var])"
    }
}

# Write to .env.docker
Set-Content -Path $envDockerFile -Value $dockerEnvContent -Encoding UTF8

Write-Host ""
Write-Host "✅ Synced JWT configuration to .env.docker" -ForegroundColor Green
Write-Host ""
Write-Host "JWT Settings:" -ForegroundColor Cyan
foreach ($var in $jwtVars) {
    if ($envVars.ContainsKey($var) -and $envVars[$var]) {
        $displayValue = $envVars[$var]
        # Mask secrets
        if ($var -eq "JWT_SECRET" -or $var -eq "JWT_PUBLIC_KEY") {
            $displayValue = $displayValue.Substring(0, [Math]::Min(10, $displayValue.Length)) + "..."
        }
        Write-Host "  $var = $displayValue" -ForegroundColor Gray
    }
}
Write-Host ""
Write-Host "Run 'docker-compose up --build' to start with updated config" -ForegroundColor Yellow
