#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# Sync JWT Configuration from .env to .env.docker
# ─────────────────────────────────────────────────────────────────
# This script copies JWT/auth settings from your local .env file
# to .env.docker, keeping Docker configuration in sync.
#
# Usage:
#   ./scripts/sync-docker-env.sh
#   npm run docker:sync
# ─────────────────────────────────────────────────────────────────

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
ENV_FILE="$ROOT_DIR/.env"
ENV_DOCKER_FILE="$ROOT_DIR/.env.docker"

# Check if .env exists
if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    exit 1
fi

# Function to get env value
get_env_value() {
    grep "^$1=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2- | head -n1
}

# JWT variables to sync
JWT_ISSUER=$(get_env_value "JWT_ISSUER")
JWT_AUDIENCE=$(get_env_value "JWT_AUDIENCE")
JWT_ALGORITHM=$(get_env_value "JWT_ALGORITHM")
JWT_SECRET=$(get_env_value "JWT_SECRET")
JWT_PUBLIC_KEY=$(get_env_value "JWT_PUBLIC_KEY")
JWT_JWKS_URI=$(get_env_value "JWT_JWKS_URI")

# Generate .env.docker
cat > "$ENV_DOCKER_FILE" << EOF
# ─────────────────────────────────────────────────────────────────
# Docker Environment Configuration
# ─────────────────────────────────────────────────────────────────
# Auto-generated by sync-docker-env.sh
# Last synced: $(date "+%Y-%m-%d %H:%M:%S")
# ─────────────────────────────────────────────────────────────────

# Application
NODE_ENV=development
PORT=3000

# PostgreSQL (Docker internal)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=backend_dev

# ─────────────────────────────────────────────────────────────────
# JWT / Authentication (synced from .env)
# ─────────────────────────────────────────────────────────────────
EOF

# Add JWT variables if they exist
[ -n "$JWT_ISSUER" ] && echo "JWT_ISSUER=$JWT_ISSUER" >> "$ENV_DOCKER_FILE"
[ -n "$JWT_AUDIENCE" ] && echo "JWT_AUDIENCE=$JWT_AUDIENCE" >> "$ENV_DOCKER_FILE"
[ -n "$JWT_ALGORITHM" ] && echo "JWT_ALGORITHM=$JWT_ALGORITHM" >> "$ENV_DOCKER_FILE"
[ -n "$JWT_SECRET" ] && echo "JWT_SECRET=$JWT_SECRET" >> "$ENV_DOCKER_FILE"
[ -n "$JWT_PUBLIC_KEY" ] && echo "JWT_PUBLIC_KEY=$JWT_PUBLIC_KEY" >> "$ENV_DOCKER_FILE"
[ -n "$JWT_JWKS_URI" ] && echo "JWT_JWKS_URI=$JWT_JWKS_URI" >> "$ENV_DOCKER_FILE"

echo ""
echo "✅ Synced JWT configuration to .env.docker"
echo ""
echo "JWT Settings:"
[ -n "$JWT_ISSUER" ] && echo "  JWT_ISSUER = $JWT_ISSUER"
[ -n "$JWT_AUDIENCE" ] && echo "  JWT_AUDIENCE = $JWT_AUDIENCE"
[ -n "$JWT_ALGORITHM" ] && echo "  JWT_ALGORITHM = $JWT_ALGORITHM"
[ -n "$JWT_JWKS_URI" ] && echo "  JWT_JWKS_URI = $JWT_JWKS_URI"
[ -n "$JWT_SECRET" ] && echo "  JWT_SECRET = ${JWT_SECRET:0:10}..."
echo ""
echo "Run 'docker-compose up --build' to start with updated config"
